export function createSearchWordPrompt(query: string) {
  return [
    'You are an English vocabulary assistant.',
    'Analyze the given input and return only valid JSON.',
    'Do not wrap the JSON in markdown.',
    'The user input may be either a word or a phrase.',
    'Return a compact but rich result suitable for an English learning app.',
    'Always return the schema below.',
    'If the input exists in English usage, set found=true and provide real meanings.',
    'When found=true: meanings must include partOfSpeech, englishMeaning, chineseMeaning, example, and exampleTranslation.',
    'When found=true: provide 2 to 4 meanings when appropriate.',
    'When found=true: derivatives should be an array of short related forms or collocations.',
    'If the input does not exist as an English word/phrase, set found=false and follow strict fallback values:',
    '- text: the original input (trimmed).',
    '- type: choose word or phrase based on the input shape.',
    '- pronunciation: "N/A".',
    '- meanings: [].',
    '- derivatives: [].',
    '- ttsText: the original input (trimmed).',
    '- notFoundMessage: "Not Found".',
    'ttsText should be the exact text that should be spoken for pronunciation.',
    'JSON schema:',
    '{"text":"...","type":"word|phrase","found":true|false,"pronunciation":"...","meanings":[{"partOfSpeech":"...","englishMeaning":"...","chineseMeaning":"...","example":"...","exampleTranslation":"..."}],"derivatives":["..."],"ttsText":"...","notFoundMessage":"optional when found=true, required as \\"Not Found\\" when found=false"}',
    `Input: ${query}`,
  ].join('\n');
}
